In [ ]:
# 1. Array from 10 to 100 with step 10
import numpy as np
arr = np.arange(10, 101, 10)
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
# 2. Create a 3 × 4 array of zeros

arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 3. Print ndim, shape, size, and dtype
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:", arr.shape)
print("size:",arr.size)
print("Data type:",arr.dtype)
print("Number of dimensions:",arr.ndim)


Shape: (2, 3)
size: 6
Data type: int64
Number of dimensions: 2


In [ ]:
# 4. Extract the last element from a 1D array
arr = np.array([10, 20, 30, 40, 50])
print("Last element:", arr[-1])

Last element: 50


In [ ]:
# 5. Select the first two columns of a 2D array
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print(arr[:, :2])


[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [6]:
# 6. Reshape 12 numbers into a 3 × 4 matrix

arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# 7. Transpose a 2 × 3 matrix
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original matrix:")
print(arr)
print("Transposed matrix:")
print(arr.T)

Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed matrix:
[[1 4]
 [2 5]
 [3 6]]


In [8]:
# 8. Multiply every element by 5
arr = np.array([1, 2, 3, 4, 5])
result = arr * 5
print(result)

[ 5 10 15 20 25]


In [9]:
# 9. Create feature matrix X with 5 samples and 3 features
X = np.array([
    [20, 30, 40],
    [60, 70, 80],
    [40, 50, 60],
    [90, 80, 70],
    [30, 40, 50]
])
print("Shape:", X.shape)

Shape: (5, 3)


In [ ]:
# 10. Calculate mean of each feature using axis=0
X = np.array([
    [20, 30, 40],
    [60, 70, 80],
    [40, 50, 60],
    [90, 80, 70],
    [30, 40, 50]
])
mean = np.mean(X, axis=0)
print("Mean:", mean)


Mean: [48. 54. 60.]


In [12]:
# 11. Filter rows where the first feature is greater than 50
X = np.array([
    [20, 30, 40],
    [60, 70, 80],
    [40, 50, 60],
    [90, 80, 70],
    [30, 40, 50]
])
print("Rows where first feature > 50:",X[X[:, 0] > 50])


Rows where first feature > 50: [[60 70 80]
 [90 80 70]]


In [14]:
# 12. Standardize every feature column
X = np.array([
    [20, 30, 40],
    [60, 70, 80],
    [40, 50, 60],
    [90, 80, 70],
    [30, 40, 50]
])
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_standardized = (X - mean) / std
print("Standardized matrix:")
print(X_standardized)

Standardized matrix:
[[-1.12815215 -1.29399328 -1.41421356]
 [ 0.48349378  0.86266219  1.41421356]
 [-0.32232919 -0.21566555  0.        ]
 [ 1.69222822  1.40182605  0.70710678]
 [-0.72524067 -0.75482941 -0.70710678]]


In [15]:
# 13. Random matrix of shape (10, 4) using fixed seed
np.random.seed(42)
X = np.random.rand(10, 4)
print(X)

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444]
 [0.59241457 0.04645041 0.60754485 0.17052412]
 [0.06505159 0.94888554 0.96563203 0.80839735]
 [0.30461377 0.09767211 0.68423303 0.44015249]]


In [17]:
# 14. Calculate X @ weights
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
weights = np.array([0.5, 1.0, 2.0])
result = X @ weights
print(result)

[ 8.5 19.  29.5]


In [18]:
#15. Add a bias vector using broadcasting

X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
bias = np.array([10, 20, 30])
result = X + bias
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [19]:
# 16. Calculate MSE between y_true and y_pred
y_true = np.array([10, 20, 30, 40])
y_pred = np.array([12, 18, 29, 42])
mse = np.mean((y_true - y_pred) ** 2)
print("MSE:", mse)

MSE: 3.25


In [20]:
# 17. Create a 28 × 28 grayscale image
image = np.zeros((28, 28))
print("Shape:", image.shape)

Shape: (28, 28)


In [21]:
# 18. Create a batch of 64 RGB images of size 224 × 224
images = np.zeros((64, 224, 224, 3))
print("Shape:", images.shape)

Shape: (64, 224, 224, 3)


In [23]:
# 19. Array containing NaN and NaN-safe mean
data = np.array([10, 20, np.nan, 30, 40])
print("NaN-Safe mean:", np.nanmean(data))
print("NaN-Safe sum:", np.nansum(data))

NaN-Safe mean: 25.0
NaN-Safe sum: 100.0


In [24]:
# 20. Difference between A * B and A @ B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Element wise multiplication:\n", A * B)
print("\n matrix multiplication:\n", A @ B)


Element wise multiplication:
 [[ 5 12]
 [21 32]]

 matrix multiplication:
 [[19 22]
 [43 50]]
